-- Eliminar tabla si existe
drop table if exists public."PRODUCTO";

-- Crear tabla PRODUCTO
create table public."PRODUCTO" (
    id bigint generated by default as identity not null,
    nombre_producto character varying(255) not null,
    marca character varying(100) not null,
    sku character varying(50) not null,
    precio integer not null check (precio >= 0),
    url_imagen character varying(500) null,
    url_producto character varying(500) null,
    fecha_creacion timestamp with time zone default CURRENT_TIMESTAMP not null,
    fecha_actualizacion timestamp with time zone default CURRENT_TIMESTAMP not null,
    categoria character varying(100) null,
    peso_gramos integer null check (peso_gramos > 0),
    sellos_advertencia character varying(50) null,
    constraint producto_pkey primary key (id),
    constraint producto_sku_unique unique (sku)
);

-- Agregar comentarios a la tabla y columnas
comment on table public."PRODUCTO" is 'Tabla que almacena información de productos de supermercado';
comment on column public."PRODUCTO".id is 'Identificador único del producto';
comment on column public."PRODUCTO".nombre_producto is 'Nombre completo del producto';
comment on column public."PRODUCTO".marca is 'Marca del producto';
comment on column public."PRODUCTO".sku is 'Código SKU único del producto';
comment on column public."PRODUCTO".precio is 'Precio del producto en pesos chilenos';
comment on column public."PRODUCTO".peso_gramos is 'Peso del producto en gramos';
comment on column public."PRODUCTO".sellos_advertencia is 'Tipo de sellos de advertencia del producto (sin_sellos, un_sello, dos_sellos)';

-- Crear índices
create index idx_producto_nombre on public."PRODUCTO" (nombre_producto);
create index idx_producto_marca on public."PRODUCTO" (marca);
create index idx_producto_sku on public."PRODUCTO" (sku);
create index idx_producto_categoria on public."PRODUCTO" (categoria);