-- Eliminar tabla si existe
drop table if exists public."TABLA_PRODUCTOS";

-- Crear tabla TABLA_PRODUCTOS
create table public."TABLA_PRODUCTOS" (
    id bigint generated by default as identity not null,
    nombre_producto character varying(255) not null,
    marca character varying(100) not null,
    sku character varying(50) not null,
    precio integer not null check (precio >= 0),
    url_imagen character varying(500) null,
    url_producto character varying(500) null,
    fecha_creacion timestamp with time zone default CURRENT_TIMESTAMP not null,
    fecha_actualizacion timestamp with time zone default CURRENT_TIMESTAMP not null,
    categoria character varying(100) null,
    peso_gramos integer null check (peso_gramos > 0),
    sellos_advertencia character varying(50) null,
    categoria_id UUID null,
    constraint producto_pkey primary key (id),
    constraint producto_sku_unique unique (sku)
);

-- Agregar comentarios a la tabla y columnas
comment on table public."TABLA_PRODUCTOS" is 'Tabla que almacena información de productos de supermercado';
comment on column public."TABLA_PRODUCTOS".id is 'Identificador único del producto';
comment on column public."TABLA_PRODUCTOS".nombre_producto is 'Nombre completo del producto';
comment on column public."TABLA_PRODUCTOS".marca is 'Marca del producto';
comment on column public."TABLA_PRODUCTOS".sku is 'Código SKU único del producto';
comment on column public."TABLA_PRODUCTOS".precio is 'Precio del producto en pesos chilenos';
comment on column public."TABLA_PRODUCTOS".peso_gramos is 'Peso del producto en gramos';
comment on column public."TABLA_PRODUCTOS".sellos_advertencia is 'Tipo de sellos de advertencia del producto (sin_sellos, un_sello, dos_sellos)';
comment on column public."TABLA_PRODUCTOS".categoria_id is 'Referencia al ID de la categoría en TABLA_CATEGORIAS';

-- Crear índices
create index idx_producto_nombre on public."TABLA_PRODUCTOS" (nombre_producto);
create index idx_producto_marca on public."TABLA_PRODUCTOS" (marca);
create index idx_producto_sku on public."TABLA_PRODUCTOS" (sku);
create index idx_producto_categoria on public."TABLA_PRODUCTOS" (categoria);
create index idx_producto_categoria_id on public."TABLA_PRODUCTOS" (categoria_id);

-- Agregar restricción de clave foránea si la tabla TABLA_CATEGORIAS ya existe
DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'TABLA_CATEGORIAS') THEN
        ALTER TABLE public."TABLA_PRODUCTOS" ADD CONSTRAINT fk_producto_categoria
            FOREIGN KEY (categoria_id) REFERENCES public."TABLA_CATEGORIAS" (id);
    END IF;
END
$$;
